print ("tip: IF you get any error run again and plz do exactly as said")
dots = "........................................................................................"
name, age, year = input ("plz type your name, age and birth year with comma in between. so i can know you batter; and plz ignore comma at the end ").split(",")
print (dots)
print(f"hello {name}. good to know your age is {age}, and you typed your birth day is {year}. thank you for that ")
print ("i can also ask you one by one like this plz give the input ")
print (dots)
name = input ("plz type your full name ")
age = input ("plz type your age ")
year = input("plz type your birth year ")
print (dots)
print (f"thank you {name}. you typed your age is {age} and you were born in {year}")
print(f"nice to meet you {name}. Let me introduce myself i am python")
print("I can do many thing, like i can reverse anything you type")
print (dots)
anything = input("plz input something hard to reverse ")
print (dots)
print(f"thats easy- {anything[ : : -1]}")
print("Andddd....I can also give you details about any word you type for example ")
print (dots)
word, character =input("type some word and a character from those words with comma in between ").split(",")
lenth = (word.replace (" ", ""))
print (dots)
print (f"this word '{word}' has exact {len(lenth)} character \nin lower case it looks like this '{word.lower()}' \nand in upper case it looks like this '{word.upper()}' \nbut it looks batter this way '{word.title()}' \nand oh! you typed '{character}' character which used {word.lower().count(character.lower())} times in those word \nand i can also reverse this word like this '{word[ : : -1]}' i already told you that you know ! \nawesome huh")
print ("and i can even tell you exact number of an word from and sentence")
print ("let me show you a random sentence try me") 
quote = "If you learn or read something that doesn't work in real life and gives no profits in real life than that is entertainment. avoid entertainment like movies, news, or any kind of none educational videos "
print (quote)
print (dots)
word = input ("type any word from above i will tell you the exact number where the word i will be counting spaces also ")
print (dots)
print (f"I found it. the word '{word}' is at {quote.find(word)}")
print (dots)
smart_name = (name.center(len(name)+4, "*"))
print (f"You are smart {smart_name} keep working like this ")